config/routes.rb
  Rails.application.routes.draw do
  resources :ubigeos
  resources :banks
  resources :bank_accounts
  resources :dependents
  resources :reniecs
  resources :requests do
    collection do
      get 'search_spouse' => 'requests#search_spouse', as: :search_spouse
      get 'spouse/' => 'requests#spouse', as: :spouse
      get 'view_observations' => 'requests#view_observations', as: :view_observations
    end
  end
  resources :job_types
  resources :economy_activities
  resources :economy_sectors
  resources :salaries
  resources :observations
  resources :observation_types
  resources :alianzas
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions', passwords:'user/passwords' },
  path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    password: 'forgot_password'
  }
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get'inicio', to: 'static_pages#home', as: :home
  get'index', to: 'static_pages#index', as: :index
  get'dashboard', to: 'static_pages#dashboard', as: :dashboard
  get'thanks', to: 'static_pages#thanks', as: :thanks
  get'pep', to: 'static_pages#pep', as: :pep
	
  get '/ubigeo/get/departamentos(.:format)'=>"ubigeos#get_departamentos"
  get '/ubigeo/get/provincias/:departamento(.:format)'=>"ubigeos#get_provincias"
  get '/ubigeo/get/distritos/:provincia(.:format)'=>"ubigeos#get_distritos"
  get '/ubigeo/get/ubigeo/:ubigeo_id(.:format)' =>"ubigeos#get_ubigeo"

  root :to => 'static_pages#home'
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :request, inverse_of: :dependents
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :set_dependent, only: [:show, :edit, :update, :destroy]

  # GET /dependents
  # GET /dependents.json
  def index
    @dependents = Dependent.all
  end

  # GET /dependents/1
  # GET /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = Dependent.new
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents
  # POST /dependents.json
  def create
    @dependent = Dependent.new(dependent_params)

    respond_to do |format|
      if @dependent.save
        format.html { redirect_to @dependent, notice: 'Dependent was successfully created.' }
        format.json { render :show, status: :created, location: @dependent }
      else
        format.html { render :new }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1
  # PATCH/PUT /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.html { redirect_to @dependent, notice: 'Dependent was successfully updated.' }
        format.json { render :show, status: :ok, location: @dependent }
      else
        format.html { render :edit }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1
  # DELETE /dependents/1.json
  def destroy
    @dependent.destroy
    respond_to do |format|
      format.html { redirect_to dependents_url, notice: 'Dependent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = Dependent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependent_params
      params.require(:dependent).permit(:request_id, :name, :last_name, :second_last_name, :birthdate, :relationship)
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_form.html.erb
<%= form_with(model: dependent, local: true) do |form| %>
  <% if dependent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dependent.errors.count, "error") %> prohibited this dependent from being saved:</h2>

      <ul>
      <% dependent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :request_id %>
    <%= form.text_field :request_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :second_last_name %>
    <%= form.text_field :second_last_name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate %>
  </div>

  <div class="field">
    <%= form.label :relationship %>
    <%= form.number_field :relationship %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dependents/edit.html.erb
<h1>Editing Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Show', @dependent %> |
<%= link_to 'Back', dependents_path %>

app/views/dependents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependents</h1>

<table>
  <thead>
    <tr>
      <th>Request</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Second last name</th>
      <th>Birthdate</th>
      <th>Relationship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependents.each do |dependent| %>
      <tr>
        <td><%= dependent.request %></td>
        <td><%= dependent.name %></td>
        <td><%= dependent.last_name %></td>
        <td><%= dependent.second_last_name %></td>
        <td><%= dependent.birthdate %></td>
        <td><%= dependent.relationship %></td>
        <td><%= link_to 'Show', dependent %></td>
        <td><%= link_to 'Edit', edit_dependent_path(dependent) %></td>
        <td><%= link_to 'Destroy', dependent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependent', new_dependent_path %>

app/views/dependents/new.html.erb
<h1>New Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Back', dependents_path %>

app/views/dependents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Request:</strong>
  <%= @dependent.request %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dependent.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @dependent.last_name %>
</p>

<p>
  <strong>Second last name:</strong>
  <%= @dependent.second_last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @dependent.birthdate %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @dependent.relationship %>
</p>

<%= link_to 'Edit', edit_dependent_path(@dependent) %> |
<%= link_to 'Back', dependents_path %>