config/routes.rb
  Rails.application.routes.draw do
  resources :ubigeos
  resources :banks
  resources :bank_accounts
  resources :dependents
  resources :reniecs
  resources :requests do
    collection do
      get 'search_spouse' => 'requests#search_spouse', as: :search_spouse
      get 'spouse/' => 'requests#spouse', as: :spouse
      get 'view_observations' => 'requests#view_observations', as: :view_observations
    end
  end
  resources :job_types
  resources :economy_activities
  resources :economy_sectors
  resources :salaries
  resources :observations
  resources :observation_types
  resources :alianzas
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions', passwords:'user/passwords' },
  path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    password: 'forgot_password'
  }
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get'inicio', to: 'static_pages#home', as: :home
  get'index', to: 'static_pages#index', as: :index
  get'dashboard', to: 'static_pages#dashboard', as: :dashboard
  get'thanks', to: 'static_pages#thanks', as: :thanks
  get'pep', to: 'static_pages#pep', as: :pep
	
  get '/ubigeo/get/departamentos(.:format)'=>"ubigeos#get_departamentos"
  get '/ubigeo/get/provincias/:departamento(.:format)'=>"ubigeos#get_provincias"
  get '/ubigeo/get/distritos/:provincia(.:format)'=>"ubigeos#get_distritos"
  get '/ubigeo/get/ubigeo/:ubigeo_id(.:format)' =>"ubigeos#get_ubigeo"

  root :to => 'static_pages#home'
end

app/models/observation.rb
class Observation < ApplicationRecord
  has_one :observation_type, dependent: :destroy
  belongs_to :request, inverse_of: :observations
end

app/models/observation_type.rb
class ObservationType < ApplicationRecord
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show ]
  load_and_authorize_resource
  before_action :set_observation, only: [:show, :edit, :update, :destroy]

  # GET /observations
  # GET /observations.json
  def index
    @observations = Observation.all
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
  end

  # GET /observations/new
  def new
    @request = Request.find(params[:request_id])
    @observation = @request.observations.build
  end

  # GET /observations/1/edit
  def edit
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(observation_params)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1
  # PATCH/PUT /observations/1.json
  def update
    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url, notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_observation
      @observation = Observation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def observation_params
      params.require(:observation).permit(:request_id, :observation_type_id, :description, :farakaki, :wsanchez, :cchinen, :akira)
    end
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/observations/_form.html.erb
<% provide(:title, "AELUCOOP - Admisión de Socios - Observaciones") %>
<%= form_with(model: observation, local: true) do |form| %>
  <% if observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% observation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="col-12 col-lg-12 col-md-12">
  <div class="row">
    <div class="form-group col-4 col-lg-4 col-md-4">
      <%= form.label :request_id, 'Solicitante', class: 'col-lg-4 col-md-4 col-sm-4 control-label' %>
    </div>
    <div class='col-lg-8 col-md-8 col-sm-8'>
      <%= form.collection_select :request_id, Request.order(:id), :id, :full_name , options = {  :prompt => 'Seleccione al Solicitante'}, html_options = { class: 'select2_demo_1 form-control' } %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-4 col-lg-4 col-md-4">
      <%= form.label :observation_type_id, 'Tipo de Observación', class: 'col-lg-4 col-md-4 col-sm-4 control-label' %>
    </div>
    <div class='col-lg-8 col-md-8 col-sm-8'>
      <%= form.collection_select :observation_type_id, ObservationType.order(:nombre), :id, :nombre , options = {  :prompt => 'Seleccione un Tipo de Observación'}, html_options = { class: 'select2_demo_1 form-control' } %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-4 col-lg-4 col-md-4">
      <%= form.label :description, "Description", class: 'col-lg-4 col-md-4 col-sm-4 control-label' %>
    </div>
    <div class='col-lg-8 col-md-8 col-sm-8'>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-12 col-lg-12 col-md-12">
      <% if can? :create, Observation %>
        <% if (current_user.email.eql? 'farakaki@aelucoop.com.pe') %>
          <%= form.check_box :farakaki %>
          <%= form.label :farakaki, "Fernando Arakaki" %>
        <% end %>
        <% if (current_user.email.eql? 'wsanchez@aelucoop.com.pe') %>
          <%= form.check_box :wsanchez %>
          <%= form.label :wsanchez, "Walter Sanchez" %>
        <% end %>
        <% if (current_user.email.eql? 'cchinen@aelucoop.com.pe') %>
          <%= form.check_box :cchinen %>
          <%= form.label :cchinen, "Carolina Chinen" %>
        <% end %>
        <% if (current_user.email.eql? 'akawakami@aelucoop.com.pe') %>
          <%= form.check_box :akira %>
          <%= form.label :akira, "Akira Kawakami" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing Observation</h1>

<%= render 'form', observation: @observation %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.html.erb
<% provide(:title, "AELUCOOP - Admisión de Socios - Observaciones") %>
<p id="notice"><%= notice %></p>
  <div class="wrapper wrapper-content animated fadeInRight no-padding">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Observaciones</h1>
        </div>
        <div class="ibox-content">
          <div class='table-responsive'>
            <table class="table table-stripped table-bordered table-hover datatable">
              <thead>
                <tr>
                  <th>DNI</th>
                  <th>Tipo Observación</th>
                  <th>Observacion</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @observations.each do |observation| %>
                  <tr>
                    <td><%= Request.find(observation.request_id).dni %></td>
                    <td><%= ObservationType.find(observation.observation_type_id).nombre %></td>
                    <td><%= observation.description %></td>
                    <td><%= link_to 'Show', observation %></td>
                    <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
                    <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

<br>
<div class='row'>
  <div class="col-lg-12">
    <%= link_to 'Nueva Observación', new_observation_path, class: 'btn btn-wm btn-success' %>
  </div>
  <%= button_to 'Volver', { controller: 'requests', action: 'index'}, method: :get, class: 'btn btn-w-m btn-info' %>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(document).ready(function() {
        load_table_controls('datatable','Observaciones');
    });
  </script>
<% end %>

app/views/observations/new.html.erb
<h1>New Observation</h1>

<%= render 'form', observation: @observation %>

<%= link_to 'Volver', requests_path, class: 'btn btn-w-m btn-info' %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Observation type:</strong>
  <%= @observation.observation_type_id %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @observation.description %>
</p>

<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>