config/routes.rb
  Rails.application.routes.draw do
  resources :ubigeos
  resources :banks
  resources :bank_accounts
  resources :dependents
  resources :reniecs
  resources :requests do
    collection do
      get 'search_spouse' => 'requests#search_spouse', as: :search_spouse
      get 'spouse/' => 'requests#spouse', as: :spouse
      get 'view_observations' => 'requests#view_observations', as: :view_observations
    end
  end
  resources :job_types
  resources :economy_activities
  resources :economy_sectors
  resources :salaries
  resources :observations
  resources :observation_types
  resources :alianzas
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions', passwords:'user/passwords' },
  path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    password: 'forgot_password'
  }
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get'inicio', to: 'static_pages#home', as: :home
  get'index', to: 'static_pages#index', as: :index
  get'dashboard', to: 'static_pages#dashboard', as: :dashboard
  get'thanks', to: 'static_pages#thanks', as: :thanks
  get'pep', to: 'static_pages#pep', as: :pep
	
  get '/ubigeo/get/departamentos(.:format)'=>"ubigeos#get_departamentos"
  get '/ubigeo/get/provincias/:departamento(.:format)'=>"ubigeos#get_provincias"
  get '/ubigeo/get/distritos/:provincia(.:format)'=>"ubigeos#get_distritos"
  get '/ubigeo/get/ubigeo/:ubigeo_id(.:format)' =>"ubigeos#get_ubigeo"

  root :to => 'static_pages#home'
end

app/models/economy_activity.rb
class EconomyActivity < ApplicationRecord
	def full_name
		"#{try(:ciiu)} - #{try(:name)}".to_s
	end

end

app/controllers/economy_activities_controller.rb
class EconomyActivitiesController < ApplicationController
  before_action :set_economy_activity, only: [:show, :edit, :update, :destroy]

  # GET /economy_activities
  # GET /economy_activities.json
  def index
    @economy_activities = EconomyActivity.all
  end

  # GET /economy_activities/1
  # GET /economy_activities/1.json
  def show
  end

  # GET /economy_activities/new
  def new
    @economy_activity = EconomyActivity.new
  end

  # GET /economy_activities/1/edit
  def edit
  end

  # POST /economy_activities
  # POST /economy_activities.json
  def create
    @economy_activity = EconomyActivity.new(economy_activity_params)

    respond_to do |format|
      if @economy_activity.save
        format.html { redirect_to @economy_activity, notice: 'Economy activity was successfully created.' }
        format.json { render :show, status: :created, location: @economy_activity }
      else
        format.html { render :new }
        format.json { render json: @economy_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /economy_activities/1
  # PATCH/PUT /economy_activities/1.json
  def update
    respond_to do |format|
      if @economy_activity.update(economy_activity_params)
        format.html { redirect_to @economy_activity, notice: 'Economy activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @economy_activity }
      else
        format.html { render :edit }
        format.json { render json: @economy_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /economy_activities/1
  # DELETE /economy_activities/1.json
  def destroy
    @economy_activity.destroy
    respond_to do |format|
      format.html { redirect_to economy_activities_url, notice: 'Economy activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_economy_activity
      @economy_activity = EconomyActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def economy_activity_params
      params.require(:economy_activity).permit(:name, :ciiu)
    end
end

app/helpers/economy_activities_helper.rb
module EconomyActivitiesHelper
end

app/views/economy_activities/_form.html.erb
<%= form_with(model: economy_activity, local: true) do |form| %>
  <% if economy_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(economy_activity.errors.count, "error") %> prohibited this economy_activity from being saved:</h2>

      <ul>
      <% economy_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ciiu %>
    <%= form.text_field :ciiu %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/economy_activities/edit.html.erb
<h1>Editing Economy Activity</h1>

<%= render 'form', economy_activity: @economy_activity %>

<%= link_to 'Show', @economy_activity %> |
<%= link_to 'Back', economy_activities_path %>

app/views/economy_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Economy Activities</h1>

<table>
  <thead>
    <tr>
      <th>CIIU</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @economy_activities.each do |economy_activity| %>
      <tr>
        <td><%= economy_activity.ciiu %></td>
        <td><%= economy_activity.name %></td>
        <td><%= link_to 'Show', economy_activity %></td>
        <td><%= link_to 'Edit', edit_economy_activity_path(economy_activity) %></td>
        <td><%= link_to 'Destroy', economy_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Economy Activity', new_economy_activity_path %>

app/views/economy_activities/new.html.erb
<h1>New Economy Activity</h1>

<%= render 'form', economy_activity: @economy_activity %>

<%= link_to 'Back', economy_activities_path %>

app/views/economy_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @economy_activity.ciiu %>
</p>

<p>
  <strong>Name:</strong>
  <%= @economy_activity.name %>
</p>

<%= link_to 'Edit', edit_economy_activity_path(@economy_activity) %> |
<%= link_to 'Back', economy_activities_path %>