config/routes.rb
  Rails.application.routes.draw do
  resources :ubigeos
  resources :banks
  resources :bank_accounts
  resources :dependents
  resources :reniecs
  resources :requests do
    collection do
      get 'search_spouse' => 'requests#search_spouse', as: :search_spouse
      get 'spouse/' => 'requests#spouse', as: :spouse
      get 'view_observations' => 'requests#view_observations', as: :view_observations
    end
  end
  resources :job_types
  resources :economy_activities
  resources :economy_sectors
  resources :salaries
  resources :observations
  resources :observation_types
  resources :alianzas
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions', passwords:'user/passwords' },
  path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    password: 'forgot_password'
  }
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get'inicio', to: 'static_pages#home', as: :home
  get'index', to: 'static_pages#index', as: :index
  get'dashboard', to: 'static_pages#dashboard', as: :dashboard
  get'thanks', to: 'static_pages#thanks', as: :thanks
  get'pep', to: 'static_pages#pep', as: :pep
	
  get '/ubigeo/get/departamentos(.:format)'=>"ubigeos#get_departamentos"
  get '/ubigeo/get/provincias/:departamento(.:format)'=>"ubigeos#get_provincias"
  get '/ubigeo/get/distritos/:provincia(.:format)'=>"ubigeos#get_distritos"
  get '/ubigeo/get/ubigeo/:ubigeo_id(.:format)' =>"ubigeos#get_ubigeo"

  root :to => 'static_pages#home'
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show ]
  load_and_authorize_resource
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:range)
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.erb
<%= form_with(model: salary, local: true) do |form| %>
  <% if salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :range %>
    <%= form.text_field :range %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salaries</h1>

<table>
  <thead>
    <tr>
      <th>Range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.range %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary', new_salary_path %>

app/views/salaries/new.html.erb
<h1>New Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Range:</strong>
  <%= @salary.range %>
</p>

<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>